CREATE TABLE STATION (
	CITYID INT PRIMARY KEY AUTO_INCREMENT,
	CITY VARCHAR(50)
);

INSERT INTO STATION(CITY)
	VALUES ('IPIRANGA'),
		('ABC'),
		('ZOOL');

SELECT CITY, CHAR_LENGTH(CITY) FROM (
    SELECT CITY FROM STATION
        ORDER BY CHAR_LENGTH(CITY) ASC, CITY ASC
        LIMIT 1
) AS T
UNION
SELECT CITY, CHAR_LENGTH(CITY) FROM (
	SELECT CITY FROM STATION
		ORDER BY CHAR_LENGTH(CITY) DESC, CITY ASC
        LIMIT 1
) AS T2;